version: '3'

services:
  node-api:
    env_file:
        "./node-api/.env"
    build:
      context: ./node-api
      dockerfile: ./Dockerfile
    image: "training/node-api"
    ports:
      - "5000:5000"
    volumes:
      - .:/node-api
  react-training:
    build:
      context: ./react-training
      dockerfile: ./Dockerfile
    image: "training/react-training"
    ports:
      - "3000:3000"
    volumes:
      - .:/react-training
    links:
      - "node-api"